sudo: required

language: cpp

services:
  - docker

before_install:
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - coveralls-lcov coverage.info  

env:
  global:
    - toolset_branch: master
    - server_type: travis
    - ros_release_name: melodic
    - ubuntu_version_name: bionic
    - used_modules: check_cache,check_build,check_install,code_coverage
    - remote_shell_script: 'https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh'

script:
  - curl -s "$( echo "$remote_shell_script" | sed 's/#/%23/g' )" | bash -x /dev/stdin "$toolset_branch" $server_type $used_modules

