image: ros:melodic-ros-core

cache:
  paths:
    - ccache/

before_script:
  - mkdir /catkin_ws/src -p && cd /catkin_ws/src
  - git clone https://github.com/danielmohansahu/cleanup-robot.git --recursive
  - cd .. && rosdep update && rosdep install --from-paths src/ -iy
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov

after_success:
  - coveralls --root .. --build-root . --verbose

catkin_make:
  stage: build
  script:
    - cd /catkin_ws
    - catkin_make
    - catkin_make run_tests
